### ISSUE TITLE
[BUG] No peer certificate when synchronizing with remote DB

### ISSUE THREAD

**Issue by bambalooon** [denzilferreira/com.aware.plugin.google.fused_location#1]
Hi!

When I'm trying to sync local DB with my remote one via Aware - sync fails with message:

```
09-09 20:48:22.078   3362-28971/com.aware.plugin.google.fused_location E/AWARE::HTTPS﹕ No peer certificate
```

It's the same for OpenWeather and ActivityRecognition plugin.
I've had same issue in my own plugin and I resolved it by upgrading plugin to use newest aware-core library.

I'll really appreciate it, if you could fix it quickly.

Best regards.

**Comment by denzilferreira** [comment]
Hi!

This is a problem with the plugins’ themselves. I need to update them to include the latest library. I’ll try to update all of them tomorrow. We had to update the SSL certificate on the client since it had expired… The new SSL certificate is now valid for 5 years.

Denzil;

**Comment by bambalooon** [comment]
Hi!

Thanks for such a quick reply. Let me know when you're done.

Best regards.

**Comment by denzilferreira** [comment]
Done updating the plugins. Make sure to update the client too.

Denzil;
